print("Atul Jain: https://www.github.com/atulj968")
# write your code below
print('Deepak Kumaar: https://github.com/deepak1011dp')
print("atul jain and deepak kumar have a github account")
print('Abhishek Mohata: https://github.com/amohata007')
print('Ashita Gaur: https://github.com/ashitagaur00')
print('Ritika Garg: https://github.com/Ritika0126')
print('Harshit Gupta: https://github.com/harshit257')
print('Riya Bankar: https://github.com/coderiya')
print('Rudransh Tripathi: https://github.com/rudranshtripathi9')
print("Harsh Joshi: https://github.com/HARSHJOSHI1417")
print("Muhammad Sameer Farooq: https://github.com/msameerfarooq")
print("Vijay Halle: https://github.com/silicon1411")
print("Aman Singh: https://github.com/peaceDude404")
print("Samkit Jain : https://github.com/samkitjain4916")
print("Sudip ghimre: https://www.github.com/sudipghmire533")
print("Meenakshi Bind:https://github.com/Meenakshi-Bind")
print("Aryan Jain: https://github.com/Rockarya")
print("Rida Ayaz:https://github.com/ridaayaz")
print("Atul Jain: https://github.com/psbankar")
print("Atul Jain: https://github.com/PRAy-d")
print ("Ashish Lalwani :https://github.com/ashishlalwani582")
print("Deepak Kumar: https://github.com/deepak1011dp")
print("Siddhant Chourasia: https://github.com/siddhant008")
